/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package s5021toxls;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Kata
 */
public class Gui extends javax.swing.JFrame {

    private File input;
    private ConverterInterface c;
    private Preferences prefs;

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        setLocationRelativeTo(null);

        prefs = Preferences.userRoot().node(this.getClass().getName());
        newFormat.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        newFormat = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("S5021toXLS");

        jButton1.setText("Forrás megnyitás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mentés");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText(" ");

        newFormat.setText("Új formátum");
        newFormat.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newFormat)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(newFormat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (c == null) {
            JOptionPane.showMessageDialog(null, "Előbb válassz forrás fájlt!");
            return;
        }
        try {
            final JFileChooser fc = new JFileChooser();
            fc.setCurrentDirectory(new File(prefs.get("defdir", "")));
            fc.setSelectedFile(new File(c.getName()));
            File output = null;
            while (output == null) {
                int res = fc.showSaveDialog(null);
                if (res == JFileChooser.APPROVE_OPTION) {
                    output = fc.getSelectedFile();
                    String extension = ".xls";
                    if (!output.getName().endsWith(extension)) {
                        output = new File(output.getAbsolutePath() + extension);
                    }

                    if (output.isFile()) {
                        int res2 = JOptionPane.showConfirmDialog(null, "Fájl létezik: " + output.getName() + "\n Felülírod?",
                                "Fájl létezik!", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                        if (res2 != JOptionPane.YES_OPTION) {
                            output = null;
                        }
                    }
                } else {
                    break;
                }

                if (output != null) {
                    prefs.put("defdir", output.getParent());
                    if (!output.getName().endsWith(".xls")) {
                        output = new File(output + ".xls");
                    }
                    c.saveToXls(output);
                    Desktop.getDesktop().open(output);
                }
            }
        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(prefs.get("defdir", "")));
        int returnVal = fc.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            input = fc.getSelectedFile();
            prefs.put("defdir", input.getParent());
//            jTextArea1.setText(fc.getSelectedFile().getAbsolutePath());
//            System.out.println(fc.getSelectedFile());
            try {
                BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(input), "Cp1252"));
                jTextArea1.read(br, null);
                br.close();
                jTextArea1.requestFocus();
                if (!newFormat.isSelected()) {
                    c = new Converter(input);
                } else {
                    c = new Converter2(input);
                }
                jLabel2.setText(c.getData().size() + " sor adat");
            } catch (Exception ex) {
                throw new RuntimeException(ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox newFormat;
    // End of variables declaration//GEN-END:variables
}
